"""Regenerate the embedded `BountyClaim` source inside `BountyRegistry.py`.

The factory must hand the child's source bytes to `gl.deploy_contract`, and the
single-file `py-genlayer` runner gives the parent no way to read a sibling file.
Rather than maintain two copies of the child by hand, `contracts/BountyClaim.py`
stays canonical and this script stamps its hex encoding into the marked block of
`contracts/BountyRegistry.py`.

    py scripts/build_bundle.py           # rewrite the block
    py scripts/build_bundle.py --check   # fail if it is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHILD = ROOT / "contracts" / "BountyClaim.py"
TARGET = ROOT / "contracts" / "BountyRegistry.py"

BEGIN = "# --- BEGIN EMBEDDED CHILD SOURCE (generated by scripts/build_bundle.py) ---"
END = "# --- END EMBEDDED CHILD SOURCE ---"
LINE_WIDTH = 88


def render_block(hex_source: str) -> str:
    """Wrap the hex payload into a parenthesised, implicitly-concatenated literal."""
    if not hex_source:
        body = '""'
    else:
        chunks = [hex_source[i: i + LINE_WIDTH]
                  for i in range(0, len(hex_source), LINE_WIDTH)]
        body = "(\n" + "".join(f'    "{chunk}"\n' for chunk in chunks) + ")"
    return f"{BEGIN}\n_CHILD_SOURCE_HEX = {body}\n{END}"


def build() -> str:
    # The child source is embedded as *bytes*, so its line endings are part of the
    # payload: a file checked out or saved with CRLF produces a different (larger)
    # bundle than the same file with LF. `contracts/*.py` are therefore kept
    # LF-normalised (see .gitattributes) and this file writes LF explicitly --
    # Python's default newline translation would turn '\n' into '\r\n' on Windows
    # and silently change the deployed artifact.
    source = CHILD.read_bytes()
    return render_block(source.hex())


def main() -> int:
    text = TARGET.read_text(encoding="utf-8")
    start = text.index(BEGIN)
    finish = text.index(END) + len(END)
    current = text[start:finish]
    wanted = build()

    if "--check" in sys.argv:
        if current == wanted:
            print("embedded child source is up to date")
            return 0
        print("ERROR: embedded child source is STALE - run scripts/build_bundle.py")
        return 1

    if current == wanted:
        print("embedded child source already up to date")
        return 0

    TARGET.write_text(text[:start] + wanted + text[finish:],
                      encoding="utf-8", newline="\n")
    payload = wanted[len(BEGIN): -len(END)]
    print(
        f"embedded {CHILD.name} into {TARGET.name} ({len(payload)} hex chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
